[versions]
agp = "8.5.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
activityCompose = "1.9.3"
compose-multiplatform = "1.7.1"
constraintLayout = "2.1.4"
coreKtx = "1.13.1"
espresso = "3.6.1"
junit = "4.13.2"
junitExt = "1.2.1"
kermit = "2.0.3"
kotlin = "2.0.21"

[libraries]
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
