[versions]
packageName = "com.digrec.hodl"
versionName = "1.1.0" # x-release-please-version
agp = "8.7.2"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
activityCompose = "1.10.1"
compose-multiplatform = "1.7.3"
constraintLayout = "2.2.1"
coreKtx = "1.15.0"
espresso = "3.6.1"
junit = "4.13.2"
junitExt = "1.2.1"
kermit = "2.0.5"
koin = "4.0.2"
kotlin = "2.1.20"
lifecycleViewmodel = "2.8.4"
navigationCompose = "2.8.0-alpha12"
splashScreen = "1.0.1"

[libraries]
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
androidx-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-composeViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
