import org.gradle.api.DefaultTask
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Gradle task that synchronizes iOS version information with project version.
 *
 * This task generates or updates the version.xcconfig file which is used by Xcode to maintain
 * consistent versioning between the apps in KMP project.
 */
open class UpdateIosVersion : DefaultTask() {

    @Input
    val versionName: Property<String> = project.objects.property(String::class.java)

    @Input
    val versionCode: Property<Int> = project.objects.property(Int::class.java)

    @OutputFile
    val versionConfigFile: Property<File> = project.objects.property(File::class.java)
        .convention(project.file("${project.rootProject.projectDir}/${VERSION_CONFIG_PATH}"))

    @TaskAction
    fun generateVersionConfig() {
        val configContent = """
            // Generated by Gradle - DO NOT EDIT!
            MARKETING_VERSION = ${versionName.get()}
            CURRENT_PROJECT_VERSION = ${versionCode.get()}
        """.trimIndent()
        versionConfigFile.get().writeText(configContent)

        logger.lifecycle("✓ Successfully generated version.xcconfig")
        logger.lifecycle("  • Config file: ${versionConfigFile.get().absolutePath}")
    }

    companion object {
        const val VERSION_CONFIG_PATH = "iosApp/Configuration/version.xcconfig"
    }
}
